package studio.forface.rxtmdbapi.models


object Fields {

    internal const val ADULT =                  "adult"
    internal const val ALSO_KNOWN_AS =          "also_knows_as"
    internal const val ALTERNATIVE_TITLES =     "alternative_titles"
    internal const val ASPECT_RATIO =           "aspect_ratio"
    internal const val BACKDROPS =              "backdrops"
    internal const val BACKDROP_PATH =          "backdrop_path"
    internal const val BELONGS_TO_COLLECTION =  "belongs_to_collection"
    internal const val BIOGRAPHY =              "biography"
    internal const val BIRTHDAY =               "birthday"
    internal const val BUDGET =                 "budget"
    internal const val CAST =                   "cast"
    internal const val CHANGE_KEYS =            "change_keys"
    internal const val CHANGES =                "changes"
    internal const val CREATED_BY =             "created_by"
    internal const val CREDITS =                "credits"
    internal const val CREW =                   "crew"
    internal const val DATES =                  "dates"
    internal const val DEATHDAY =               "deathday"
    internal const val DESCRIPTION =            "description"
    internal const val EPISODE_RUN_TIME =       "episode_run_time"
    internal const val EXPIRES_AT =             "expires_at"
    internal const val EXTERNAL_IDS =           "external_ids"
    internal const val FILE_PATH =              "file_path"
    internal const val FILE_TYPE =              "file_type"
    internal const val FIRST_AIR_DATE =         "first_air_date"
    internal const val GENDER =                 "gender"
    internal const val GENRES =                 "genres"
    internal const val GUEST =                  "guest"
    internal const val GUEST_SESSION_ID =       "guest_session_id"
    internal const val HEADQUARTERS =           "headquarters"
    internal const val HEIGHT =                 "height"
    internal const val HOMEPAGE =               "homepage"
    internal const val ID =                     "id"
    internal const val IN_PRODUCTION =          "in_production"
    internal const val IMAGES =                 "images"
    internal const val ISO_639_1 =              "iso_639_1"
    internal const val KEYWORDS =               "keywords"
    internal const val KNOWN_FOR =              "knows_for"
    internal const val LANGUAGES =              "languages"
    internal const val LAST_AIR_DATE =          "last_air_date"
    internal const val LISTS =                  "lists"
    internal const val LOGO_PATH =              "logo_path"
    internal const val LOGOS =                  "logos"
    internal const val MAXIMUM =                "maximum"
    internal const val MEDIA_TYPE =             "media_type"
    internal const val MINIMUM =                "minimum"
    internal const val NAME =                   "name"
    internal const val NETWORKS =               "networks"
    internal const val NUMBER_OF_EPISODES =     "number_of_episodes"
    internal const val NUMBER_OF_SEASONS =      "number_of_seasons"
    internal const val ORIGIN_COUNTRY =         "origin_country"
    internal const val ORIGINAL_LANGUAGE =      "original_language"
    internal const val ORIGINAL_NAME =          "original_name"
    internal const val ORIGINAL_TITLE =         "original_title"
    internal const val OVERVIEW =               "overview"
    internal const val PARENT_COMPANY =         "parent_company"
    internal const val PARTS =                  "parts"
    internal const val PLACE_OF_BIRTH =         "place_of_birth"
    internal const val POPULARITY =             "popularity"
    internal const val POSTERS =                "posters"
    internal const val POSTER_PATH =            "poster_path"
    internal const val PRODUCTION_COMPANIES =   "production_companies"
    internal const val PRODUCTION_COUNTRIES =   "production_countries"
    internal const val PROFILE_PATH =           "profile_path"
    internal const val PROFILES =               "profiles"
    internal const val RECOMMENDATIONS =        "recommendations"
    internal const val RELEASE_DATE =           "release_date"
    internal const val RELEASE_DATES =          "release_dates"
    internal const val RESULTS =                "results"
    internal const val REVENUE =                "revenue"
    internal const val REVIEWS =                "reviews"
    internal const val RUNTIME =                "runtime"
    internal const val SEASONS =                "seasons"
    internal const val SESSION_ID =             "session_id"
    internal const val SIMILAR =                "similar"
    internal const val SPOKEN_LANGUAGES =       "spoken_languages"
    internal const val STATUS =                 "status"
    internal const val STILLS =                 "stills"
    internal const val SUCCESS =                "success"
    internal const val TAGLINE =                "tagline"
    internal const val TIMESTAMP =              "timestamp"
    internal const val TITLE =                  "title"
    internal const val TITLES =                 "titles"
    internal const val TYPE =                   "type"
    internal const val TRANSLATIONS =           "translations"
    internal const val VIDEO =                  "video"
    internal const val VIDEOS =                 "videos"
    internal const val VOTE_AVERAGE =           "vote_average"
    internal const val VOTE_COUNT =             "vote_count"
    internal const val WIDTH =                  "width"

    // Images config.
    internal const val BASE_URL =               "base_url"
    internal const val SECURE_BASE_URL =        "secure_base_url"
    internal const val BACKDROP_SIZES =         "backdrop_sizes"
    internal const val LOGO_SIZES =             "logo_sizes"
    internal const val POSTER_SIZES =           "poster_sizes"
    internal const val PROFILE_SIZES =          "profile_sizes"
    internal const val STILL_SIZES =            "still_sizes"

    // External IDS.
    internal const val FACEBOOK_ID =            "facebook_id"
    internal const val FREEBASE_ID =            "freebase_id"
    internal const val FREEBASE_MID =           "freebase_mid"
    internal const val IMDB_ID =                "imdb_id"
    internal const val INSTAGRAM_ID =           "instagram_id"
    internal const val TVDB_ID =                "tvdb_id"
    internal const val TVRAGE_ID =              "tvrage_id"
    internal const val TWITTER_ID =             "twitter_id"

}