package studio.forface.rxtmdbapi.models


object Fields {

    internal const val ADULT =                  "adult"
    internal const val ALTERNATIVE_TITLES =     "alternative_titles"
    internal const val BACKDROPS =              "backdrops"
    internal const val BACKDROP_PATH =          "backdrop_path"
    internal const val BELONGS_TO_COLLECTION =  "belongs_to_collection"
    internal const val BUDGET =                 "budget"
    internal const val CAST =                   "cast"
    internal const val CHANGES =                "changes"
    internal const val CREDITS =                "credits"
    internal const val CREW =                   "crew"
    internal const val DATES =                  "dates"
    internal const val EXTERNAL_IDS =           "external_ids"
    internal const val GENRES =                 "genres"
    internal const val HOMEPAGE =               "homepage"
    internal const val ID =                     "id"
    internal const val IMAGES =                 "images"
    internal const val KEYWORDS =               "keywords"
    internal const val LISTS =                  "lists"
    internal const val MAXIMUM =                "maximum"
    internal const val MINIMUM =                "minimum"
    internal const val NAME =                   "name"
    internal const val ORIGINAL_LANGUAGE =      "original_language"
    internal const val ORIGINAL_TITLE =         "original_title"
    internal const val OVERVIEW =               "overview"
    internal const val PARTS =                  "parts"
    internal const val POPULARITY =             "popularity"
    internal const val POSTERS =                "posters"
    internal const val POSTER_PATH =            "poster_path"
    internal const val PRODUCTION_COMPANIES =   "production_companies"
    internal const val PRODUCTION_COUNTRIES =   "production_countries"
    internal const val RECOMMENDATIONS =        "recommendations"
    internal const val RELEASE_DATE =           "release_date"
    internal const val RELEASE_DATES =          "release_dates"
    internal const val RESULTS =                "results"
    internal const val REVENUE =                "revenue"
    internal const val REVIEWS =                "reviews"
    internal const val RUNTIME =                "runtime"
    internal const val SIMILAR =                "similar"
    internal const val SPOKEN_LANGUAGES =       "spoken_languages"
    internal const val STATUS =                 "status"
    internal const val TAGLINE =                "tagline"
    internal const val TITLE =                  "title"
    internal const val TITLES =                 "titles"
    internal const val TRANSLATIONS =           "translations"
    internal const val VIDEO =                  "video"
    internal const val VIDEOS =                 "videos"
    internal const val VOTE_AVERAGE =           "vote_average"
    internal const val VOTE_COUNT =             "vote_count"

    internal const val FACEBOOK_ID =            "facebook_id"
    internal const val FREEBASE_ID =            "freebase_id"
    internal const val FREEBASE_MID =           "freebase_mid"
    internal const val IMDB_ID =                "imdb_id"
    internal const val INSTAGRAM_ID =           "instagram_id"
    internal const val TVDB_ID =                "tvdb_id"
    internal const val TVRAGE_ID =              "tvrage_id"
    internal const val TWITTER_ID =             "twitter_id"

}